#!/bin/bash

# Update the variable when necessary
# Besids that you have to update the "RhelCentos-VEN-Install-PS-v1.0.sh" script for the correct variables

# Script to be run in the workload
set exarg1 "RhelCentos-VEN-Install-PS-v1.0.sh"

# Variable to check if VEN has installed
set exarg2 "/opt/illumio_ven_data/etc/agent_id.cfg"

# Root CA cert, changed it when necessary
set exarg3 "root.illumioeval.com.crt"

# The expect script that doing the job for VEN installation
set exarg4 "veninstall.expect"
